@startuml

skinparam sequence {
	ArrowColor #535353
	LifeLineBorderColor Black
	LifeLineBackgroundColor #eff5ff

	ParticipantBorderColor Black
	ParticipantBackgroundColor #eff5ff

}
skinparam note{
    BorderColor #ff7070
    BackgroundColor #fff9f9
}

participant Enemy
participant Bullet
participant Me
activate Enemy
activate Me

title 弾の生成の流れ\n

note over of Bullet
	事前に素材として
    用意しておく
end note

group Enemy Start()
    Enemy <- Bullet : 弾を読み込む
end
group Enemy Update()
    Enemy <- Me : 自機の現在位置を取得する
    Enemy -> Bullet : 自機の現在位置をもとに生成する

    activate Bullet
    group Bullet Update()
        Bullet -> Bullet : 横に進む
    end
end

@enduml
