@startuml

skinparam sequence {
	ArrowColor #535353
	LifeLineBorderColor Black
	LifeLineBackgroundColor #eff5ff

	ParticipantBorderColor Black
	ParticipantBackgroundColor #eff5ff

}
skinparam note{
    BorderColor #ff7070
    BackgroundColor #fff9f9
}

participant 敵
participant 弾
participant プレイヤー
activate 敵
activate プレイヤー

title 弾の生成の流れ\n

note over of 弾
	事前に素材として
    用意しておく
end note

group 敵 Start()
    敵 <- 弾 : 弾を読み込む
end
group 敵 Update()
    敵 <- プレイヤー : プレイヤーの現在位置を取得する
    敵 -> 弾 : プレイヤーの現在位置をもとに生成する

    activate 弾
    group 弾 Update()
        弾 -> 弾 : 横に進む
    end
end

@enduml
